#!/bin/bash
# wp-setup.sh — Runs inside the wp-cli container.
# Waits for wp-config.php + MySQL, imports the seed DB, then patches the
# admin credentials using values from .env so no secrets live in the dump.

set -euo pipefail

log() { echo "[wp-setup $(date '+%H:%M:%S')] $*"; }

MAX_TRIES=60

# ── 0. Disable SSL for MariaDB CLI tools ─────────────────────────
# wp-cli's image ships MariaDB client tools which reject MySQL 8's
# auto-generated self-signed cert. Since we're on an internal Docker
# network, SSL adds nothing. Write a client config to skip it.
cat > /tmp/.my.cnf << 'MYCNF'
[client]
ssl=0
[mysqlcheck]
ssl=0
[mysqldump]
ssl=0
[mysql]
ssl=0
MYCNF
export HOME=/tmp

# ── 1. Wait for wp-config.php to be generated by the WP container ─
log "Waiting for wp-config.php..."
for i in $(seq 1 $MAX_TRIES); do
  if [ -f /var/www/html/wp-config.php ]; then
    log "wp-config.php found (attempt $i)."
    break
  fi
  if [ "$i" -eq "$MAX_TRIES" ]; then
    log "ERROR: wp-config.php not found after $MAX_TRIES attempts."
    exit 1
  fi
  sleep 3
done

# ── 2. Wait for MySQL to actually accept queries ─────────────────
log "Waiting for MySQL at ${WORDPRESS_DB_HOST:-mysql}..."
for i in $(seq 1 $MAX_TRIES); do
  if wp db check --quiet 2>/dev/null; then
    log "MySQL is ready (attempt $i)."
    break
  fi
  if [ "$i" -eq "$MAX_TRIES" ]; then
    log "ERROR: MySQL not reachable after $MAX_TRIES attempts."
    log "Debug — last wp db check output:"
    wp db check 2>&1 || true
    exit 1
  fi
  sleep 3
done

# ── 3. Import the seed SQL if the DB is empty ────────────────────
TABLE_COUNT=$(wp db query "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${WORDPRESS_DB_NAME}';" --skip-column-names 2>/dev/null || echo "0")

if [ "$TABLE_COUNT" -lt 2 ]; then
  log "Database looks empty ($TABLE_COUNT tables) — importing seed SQL..."
  if [ -f /docker-entrypoint-initdb/seed.sql ]; then
    wp db import /docker-entrypoint-initdb/seed.sql
    log "Seed SQL imported successfully."
  else
    log "No seed.sql found — running fresh wp core install..."
    wp core install \
      --url="${WP_URL}" \
      --title="${WP_TITLE}" \
      --admin_user="${WP_ADMIN_USER}" \
      --admin_password="${WP_ADMIN_PASSWORD}" \
      --admin_email="${WP_ADMIN_EMAIL}" \
      --skip-email
    log "Fresh WordPress installed."
    exit 0
  fi
else
  log "Database already has $TABLE_COUNT tables — skipping import."
fi

# ── 4. Patch admin credentials from .env ─────────────────────────
log "Updating admin user (ID 1) from environment variables..."

wp user update 1 \
  --user_pass="${WP_ADMIN_PASSWORD}" \
  --display_name="${WP_ADMIN_USER}" \
  --user_email="${WP_ADMIN_EMAIL}" \
  --skip-email

log "Admin credentials updated from .env."

# ── 5. Patch site URL ───────────────────────────────────────────
log "Setting site URL to ${WP_URL}..."
wp option update siteurl "${WP_URL}" 2>/dev/null || true
wp option update home "${WP_URL}" 2>/dev/null || true

# ── 6. Flush ─────────────────────────────────────────────────────
wp rewrite flush --hard 2>/dev/null || true
wp cache flush 2>/dev/null || true

log "=============================="
log "  WordPress setup complete!"
log "  URL:   ${WP_URL}"
log "  Admin: ${WP_ADMIN_USER}"
log "=============================="
